Add connections by IP
pixie-labs/pixie pull request #111
Opened 2020-09-11 22:11 UTC by philkuz

![image](https://user-images.githubusercontent.com/5456019/92977020-b5004700-f440-11ea-9bf2-e0e0b79f3a53.png)
Connections by IP helps you find the Kubernetes pods that talk to external IPs and displays them as a graph.

Helpful for finding database clients, users of an external API, etc.

2020-09-11 22:15 UTC, philkuz commented
I think this supersedes #107

2020-09-13 02:18 UTC, ishanmkh requested changes
@philkuz i get this error when testing on any 0.4.11 vizier 
<img width="747" alt="Screen Shot 2020-09-12 at 7 17 13 PM" src="https://user-images.githubusercontent.com/19366041/93008715-b149ee80-f52c-11ea-937f-c8b08e5b1b18.png">

2020-09-14 17:41 UTC, philkuz commented
> @philkuz i get this error when testing on any 0.4.11 vizier
> <img alt="Screen Shot 2020-09-12 at 7 17 13 PM" width="747" src="https://user-images.githubusercontent.com/19366041/93008715-b149ee80-f52c-11ea-937f-c8b08e5b1b18.png">

should work in 0.4.12

2020-09-15 04:38 UTC, ishanmkh approved these changes
@philkuz  👍 works well.

2020-09-15 04:38 UTC, merged