[px/node] add widget to display node the pod runs on
pixie-labs/pixie pull request #158
Opened 2020-10-16 01:53 UTC by htroisi

![image](https://user-images.githubusercontent.com/66266496/96203823-ad3c3280-0f17-11eb-8027-92fd0e9dd65d.png)

2020-10-16 02:56 UTC, nserrino commented on pxl_scripts/px/pod/pod.pxl
> +    df = df.groupby(['name']).agg()
nit: you can omit the bracket and just say 'name' when the list only has one element

2020-10-16 03:16 UTC, nserrino approved these changes

2020-10-16 16:03 UTC, philkuz commented
Change the git title to px/pod rather than px/node.


Also I would also add info abt the service that runs the pod. Maybe something like Pod Metadata?

2020-10-16 16:04 UTC, philkuz requested changes
rename pr and add more metadata to the table. We can also discuss over slack

2020-10-16 17:56 UTC, htroisi commented
![image](https://user-images.githubusercontent.com/66266496/96292535-3f871980-0f9e-11eb-8c2b-85455b4e2ae6.png)

2020-10-19 21:19 UTC, zasgar commented
I think this is ok for now, but we should probably have a custom widget type to make the formatting better.

2020-10-19 21:19 UTC, zasgar approved these changes

2020-10-19 21:19 UTC, merged