Increase readability of px/funcs
pixie-labs/pixie pull request #159
Opened 2020-10-16 18:12 UTC by htroisi

By increasing the table heights.

2020-10-16 23:12 UTC, philkuz requested changes

2020-10-16 23:12 UTC, philkuz commented on pxl_scripts/px/funcs/vis.json
> +}
need a space at the end.

2020-10-16 23:12 UTC, philkuz commented on pxl_scripts/px/funcs/funcs.pxl
> +	return px.GetUDTFList()
space at end of file

2020-11-19 22:02 UTC, philkuz approved these changes

2020-12-10 02:46 UTC, zasgar approved these changes

2020-12-10 02:46 UTC, merged